DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_CODE` INT(10) NOT NULL,
  `USER_EMAIL` VARCHAR(20) NOT NULL,
  `USER_NAME` VARCHAR(20) NOT NULL,
  `USER_PASS` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USER_ID`) USING BTREE,
  UNIQUE KEY `UNI_USER_CODE` (`USER_CODE`),
  UNIQUE KEY `UNI_USER_EMAIL` (`USER_EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;